// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXE9yIjddyF9Mc9M3y_XKYrlpMVdub3vY',
    appId: '1:737235152460:web:a6ad334d3cb38ca66a4ee9',
    messagingSenderId: '737235152460',
    projectId: 'pyracheck',
    authDomain: 'pyracheck.firebaseapp.com',
    storageBucket: 'pyracheck.firebasestorage.app',
    measurementId: 'G-NPK47PB73V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZvMSdEXFDuaYV4OSOF0tMYXEsU5wvBAE',
    appId: '1:737235152460:android:cf1975d0a78996526a4ee9',
    messagingSenderId: '737235152460',
    projectId: 'pyracheck',
    storageBucket: 'pyracheck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9RoHUWGl-yjEGP_U3hgkTv8dsZb1fYds',
    appId: '1:737235152460:ios:2176b3f58339bef56a4ee9',
    messagingSenderId: '737235152460',
    projectId: 'pyracheck',
    storageBucket: 'pyracheck.firebasestorage.app',
    iosClientId: '737235152460-9eb6rohmvijguh005rha6778j8ab79nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9RoHUWGl-yjEGP_U3hgkTv8dsZb1fYds',
    appId: '1:737235152460:ios:2176b3f58339bef56a4ee9',
    messagingSenderId: '737235152460',
    projectId: 'pyracheck',
    storageBucket: 'pyracheck.firebasestorage.app',
    iosClientId: '737235152460-9eb6rohmvijguh005rha6778j8ab79nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXE9yIjddyF9Mc9M3y_XKYrlpMVdub3vY',
    appId: '1:737235152460:web:e6a6703b59152e046a4ee9',
    messagingSenderId: '737235152460',
    projectId: 'pyracheck',
    authDomain: 'pyracheck.firebaseapp.com',
    storageBucket: 'pyracheck.firebasestorage.app',
    measurementId: 'G-10ZPEDSF59',
  );

}